// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srv/authsrv/proto/auth/auth.proto

package go_micro_srv_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Company              string   `protobuf:"bytes,3,opt,name=company,proto3" json:"company,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_b76891bfcd0ceff7, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_b76891bfcd0ceff7, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type CreateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b76891bfcd0ceff7, []int{2}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type GetUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b76891bfcd0ceff7, []int{3}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type GetUsersResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersResponse) Reset()         { *m = GetUsersResponse{} }
func (m *GetUsersResponse) String() string { return proto.CompactTextString(m) }
func (*GetUsersResponse) ProtoMessage()    {}
func (*GetUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b76891bfcd0ceff7, []int{4}
}

func (m *GetUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersResponse.Unmarshal(m, b)
}
func (m *GetUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersResponse.Marshal(b, m, deterministic)
}
func (m *GetUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersResponse.Merge(m, src)
}
func (m *GetUsersResponse) XXX_Size() int {
	return xxx_messageInfo_GetUsersResponse.Size(m)
}
func (m *GetUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersResponse proto.InternalMessageInfo

func (m *GetUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_b76891bfcd0ceff7, []int{5}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Token) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func init() {
	proto.RegisterType((*User)(nil), "go.micro.srv.user.User")
	proto.RegisterType((*Request)(nil), "go.micro.srv.user.Request")
	proto.RegisterType((*CreateUserResponse)(nil), "go.micro.srv.user.CreateUserResponse")
	proto.RegisterType((*GetUserResponse)(nil), "go.micro.srv.user.GetUserResponse")
	proto.RegisterType((*GetUsersResponse)(nil), "go.micro.srv.user.GetUsersResponse")
	proto.RegisterType((*Token)(nil), "go.micro.srv.user.Token")
}

func init() { proto.RegisterFile("srv/authsrv/proto/auth/auth.proto", fileDescriptor_b76891bfcd0ceff7) }

var fileDescriptor_b76891bfcd0ceff7 = []byte{
	// 355 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x5f, 0x4b, 0xfb, 0x30,
	0x14, 0xdd, 0xba, 0x76, 0x7f, 0xee, 0xf8, 0xfd, 0xd4, 0x20, 0x18, 0xfa, 0x34, 0x23, 0x82, 0x20,
	0x56, 0xd8, 0x1e, 0x05, 0xa1, 0xa8, 0x0c, 0xf4, 0xad, 0xfe, 0x79, 0x8f, 0xeb, 0xc5, 0x15, 0xdb,
	0xa6, 0x26, 0x69, 0xc5, 0x6f, 0xed, 0x47, 0x90, 0xa4, 0x73, 0x88, 0x6b, 0xf7, 0xe0, 0x4b, 0x9b,
	0x73, 0xcf, 0xb9, 0xa7, 0x87, 0x53, 0x02, 0x87, 0x4a, 0x56, 0xe7, 0xbc, 0xd4, 0x4b, 0xf3, 0x2e,
	0xa4, 0xd0, 0xc2, 0x22, 0xfb, 0x08, 0x2c, 0x26, 0x7b, 0x2f, 0x22, 0xc8, 0x92, 0x85, 0x14, 0x81,
	0x92, 0x55, 0x50, 0x2a, 0x94, 0xac, 0x02, 0xf7, 0x51, 0xa1, 0x24, 0xff, 0xc1, 0x49, 0x62, 0xda,
	0x9d, 0x74, 0x4f, 0x46, 0x91, 0x93, 0xc4, 0x84, 0x80, 0x9b, 0xf3, 0x0c, 0xa9, 0x63, 0x27, 0xf6,
	0x4c, 0x28, 0x0c, 0x16, 0x22, 0x2b, 0x78, 0xfe, 0x41, 0x7b, 0x76, 0xfc, 0x0d, 0xc9, 0x3e, 0x78,
	0x98, 0xf1, 0x24, 0xa5, 0xae, 0x9d, 0xd7, 0x80, 0xf8, 0x30, 0x2c, 0xb8, 0x52, 0xef, 0x42, 0xc6,
	0xd4, 0xb3, 0xc4, 0x1a, 0xb3, 0x11, 0x0c, 0x22, 0x7c, 0x2b, 0x51, 0x69, 0x16, 0x02, 0xb9, 0x92,
	0xc8, 0x35, 0x9a, 0x20, 0x11, 0xaa, 0x42, 0xe4, 0x0a, 0xc9, 0x29, 0xb8, 0x26, 0xa0, 0x8d, 0x34,
	0x9e, 0x1e, 0x04, 0x1b, 0xd1, 0x03, 0x2b, 0xb7, 0x22, 0x76, 0x09, 0x3b, 0x73, 0xd4, 0x7f, 0xdf,
	0x0f, 0x61, 0x77, 0xb5, 0xaf, 0xd6, 0x06, 0x67, 0xe0, 0x19, 0x4e, 0xd1, 0xee, 0xa4, 0xb7, 0xcd,
	0xa1, 0x56, 0xb1, 0x19, 0x78, 0x0f, 0xe2, 0x15, 0x73, 0xd3, 0x85, 0x36, 0x87, 0x55, 0x99, 0x35,
	0x30, 0xd3, 0x8a, 0xa7, 0x49, 0x6c, 0x0b, 0x1d, 0x46, 0x35, 0x98, 0x7e, 0x3a, 0x30, 0x36, 0x26,
	0xf7, 0x28, 0xab, 0x64, 0x81, 0xe4, 0x16, 0xfa, 0x75, 0x15, 0xa4, 0xed, 0x73, 0xfe, 0x71, 0x03,
	0xb1, 0x59, 0x1f, 0xeb, 0x90, 0x6b, 0xe8, 0xcd, 0x51, 0xb7, 0x1b, 0xb1, 0x06, 0xe2, 0x57, 0x89,
	0xac, 0x43, 0xee, 0xa0, 0x3f, 0x47, 0x1d, 0xa6, 0x29, 0xf1, 0x1b, 0xf4, 0xab, 0x5f, 0xe8, 0x1f,
	0xb5, 0x7b, 0xa9, 0x1f, 0x66, 0x17, 0xe0, 0x86, 0xa5, 0x5e, 0xb6, 0x67, 0xa2, 0x0d, 0x84, 0x6d,
	0x95, 0x75, 0xc8, 0x0d, 0xfc, 0x7b, 0x32, 0xa5, 0x71, 0x8d, 0x75, 0xd1, 0xad, 0xe2, 0x6d, 0x36,
	0xcf, 0x7d, 0x7b, 0x15, 0x66, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x59, 0xad, 0x7a, 0xfd, 0x2f,
	0x03, 0x00, 0x00,
}
