services:
    authapi:
        build: ./api/authapi
        command: --registry=etcd --registry_address=etcd:2379
        container_name: authapi
        depends_on:
            - authsrv
        links:
            - etcd
        #    authcli:
        #        build: ./cli/authcli
        #        container_name: authcli
        #        command: --registry=etcd --registry_address=etcd:2379
        #        depends_on:
        #            - authsrv
        #        links:
        #          - etcd
        ports:
            - 8000:8000
        restart: unless-stopped
    authsrv:
        build: ./srv/authsrv
        command: --registry=etcd --registry_address=etcd:2379
        container_name: authsrv
        depends_on:
            - datastore
        environment:
            DB_HOST: datastore:27017
        links:
            - etcd
        restart: unless-stopped
        volumes:
            - ./logs:/logs
    datastore:
        image: mongo:4.2.2-bionic
        ports:
            - 27017:27017
        #    mongo-express:
        #        image: mongo-express:0.49.0
        #        container_name: rpcserver_mongo_express
        #        ports:
        #            - 8081:8081
        #        environment:
        #            ME_CONFIG_MONGODB_ADMINPASSWORD: password
        #            ME_CONFIG_MONGODB_ADMINUSERNAME: root
        #            ME_CONFIG_MONGODB_SERVER: mongo1,mongo2,mongo3
        #        depends_on:
        #            - mongo1
        #            - mongo2
        #            - mongo3
        #        restart: unless-stopped
        #    mongo1:
        #        image: mongo:4.2.2-bionic
        #        entrypoint: [/usr/bin/mongod, --bind_ip_all, --replSet, rs0]
        #        container_name: rpcserver_mongo1
        #        volumes:
        #            - ./docker/mongo/root:/root:ro
        #        expose:
        #            - 27017
        #        ports:
        #            - 27017:27017
        #        environment:
        #            MONGO_INITDB_DATABASE: admin
        #            MONGO_INITDB_ROOT_PASSWORD: password
        #            MONGO_INITDB_ROOT_USERNAME: root
        #        hostname: mongo1
        #        depends_on:
        #            - mongo2
        #            - mongo3
        #        restart: unless-stopped
        #    mongo2:
        #        image: mongo:4.2.2-bionic
        #        entrypoint: [/usr/bin/mongod, --bind_ip_all, --replSet, rs0]
        #        container_name: rpcserver_mongo2
        #        expose:
        #            - 27017
        #        ports:
        #            - 27018:27017
        #        hostname: mongo2
        #        depends_on:
        #            - mongo3
        #        restart: unless-stopped
        #    mongo3:
        #        image: mongo:4.2.2-bionic
        #        entrypoint: [/usr/bin/mongod, --bind_ip_all, --replSet, rs0]
        #        container_name: rpcserver_mongo3
        #        expose: 
        #            - 27017
        #        ports:
        #            - 27019:27017
        #        hostname: mongo3
        #        restart: unless-stopped
        restart: unless-stopped
    etcd:
        image: bitnami/etcd:latest
        ports:
            - 2379:2379
            - 2380:2380
        environment:
            - ALLOW_NONE_AUTHENTICATION=yes
            - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
        restart: unless-stopped
    micro:
        image: microhq/micro:latest
        command: --registry=etcd --registry_address=etcd:2379 api --handler=rpc
        links:
            - etcd
        ports:
            - 8080:8080
        restart: unless-stopped
