version: '3.7'

services:
    mongo-express:
        image: mongo-express:0.49.0
        container_name: rpcserver_mongo_express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_SERVER: mongo1,mongo2,mongo3
        depends_on:
            - mongo1
            - mongo2
            - mongo3
        restart: unless-stopped
    mongo1:
        image: mongo:4.2.2-bionic
        entrypoint: [/usr/bin/mongod, --bind_ip_all, --replSet, rs0]
        container_name: rpcserver_mongo1
        volumes:
            - ./docker/mongo/root:/root:ro
        expose:
            - 27017
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_DATABASE: admin
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_ROOT_USERNAME: root
        hostname: mongo1
        depends_on:
            - mongo2
            - mongo3
        restart: unless-stopped
    mongo2:
        image: mongo:4.2.2-bionic
        entrypoint: [/usr/bin/mongod, --bind_ip_all, --replSet, rs0]
        container_name: rpcserver_mongo2
        expose:
            - 27017
        ports:
            - 27018:27017
        hostname: mongo2
        depends_on:
            - mongo3
        restart: unless-stopped
    mongo3:
        image: mongo:4.2.2-bionic
        entrypoint: [/usr/bin/mongod, --bind_ip_all, --replSet, rs0]
        container_name: rpcserver_mongo3
        expose: 
            - 27017
        ports:
            - 27019:27017
        hostname: mongo3
        restart: unless-stopped
    srv:
        build: ./srv
        container_name: rpcserver_srv
        depends_on:
            - mongo-express
        environment:
            DB_HOST: mongo1,mongo2,mongo3:27017/?replicaSet=rs0
            MICRO_ADDRESS: :50051
            MICRO_REGISTRY: mdns
        ports:
            - 50052:50051
