settings:
    files:
        outputs:
            status: false
            path: ''
            name: .r.outputs.log
        logs:
            status: false
            path: ''
            name: .r.logs.log
        errors:
            status: false
            path: ''
            name: .r.errors.log
    legacy:
        force: false
        interval: 0s
schema:
    -   name: authcli
        path: .
        commands:
            install:
                status: true
                method: go build -o build/authcli
            run:
                status: true
                method: build/authcli
        args:
            - --registry=etcd 
            - --registry_address=http://localhost:2379 
            - api
        watcher:
            extensions:
                - go
            paths:
                - /
            ignore:
                paths:
                    - .git
                    - .realize
                    - .idea
                    - docker
